name: CI

on: [push, pull_request]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v3.2.0
      with:
        clang-format-version: '11'
        check-path: 'src'
  build-unix:
    strategy:
      fail-fast: false
      matrix:
        configuration: [clang-debug, clang-release]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Conan
      run: pip install conan
    - name: Build
      uses: lukka/run-cmake@v3
      with:
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [msvc-debug, msvc-release, clang-debug, clang-release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Conan
      run: pip install conan
    - name: Build
      uses: lukka/run-cmake@v3
      with:
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'